site_name: WPC Technology Documentation

repo_name: jackveney/wpc-tech-docs
repo_url: https://github.com/jackveney/wpc-tech-docs
edit_uri: ""
extra_css:
  - 'css/extra.css'

extra:
  version:
    provider: mike

site_description: A reference for the technology located in Mackey Hall used for running and livestreaming services.

site_author: Jack Veney
theme:
  name: material
  custom_dir: material/
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: assets/WPC_logo.png
  favicon: assets/WPC_logo.png
  icon:
    repo: fontawesome/brands/github
  language: en
  static_templates:
    - 404.html

markdown_extensions:
  - tables
  - pymdownx.keys
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

copyright: Copyright &copy; 2023 Jack Veney - Westminster Presbyterian Church Wooster, Ohio
plugins:
  - search:
      lang: en
  - social:
      cards: !ENV [CARDS, false]
  - redirects:
      redirect_maps:
        tech-docs.md: docs/index.md
        docs/computer/streamdeck/PTZ_camera/presets_list.md: docs/cameras/PTZ/presets_list.md
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true
  - with-pdf:
      #author: WHO
      #copyright: ANY TEXT
      #
      cover: true
      back_cover: true
      cover_title: Technology Documentation
      cover_subtitle: Westminster Presbyterian Church - Mackey Hall Technology
      cover_logo: assets/images/banner.png
      #custom_template_path: TEMPLATES PATH
      #
      toc_title: Table of Contents
      #heading_shift: false
      toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      exclude_pages:
        - "changelog/"
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      two_columns_level: 3
      #
      #render_js: true
      #headless_chrome_path: headless-chromium
      #
      output_path: pdf/document.pdf
      #enabled_if_env: ENABLE_PDF_EXPORT
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ""
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js

# Page tree
nav:
  - Home: index.md
  - About: 
      - About:   about.md
      - Changelog: changelog.md
  - General Instructions:
    - docs/general/index.md
    - Listing of Technology Hardware Parts: docs/general/parts-listing.md
    - Switching To COW Internet: docs/general/internet.md
    - Setting Up and Powering On Computer / Cameras / Sound System / Projector: docs/general/setting-up-powering-on.md
    - Connecting iPad to Sound System: docs/general/ipad-sound-system.md
    - Fixing Proclaim for OBS Studio: docs/general/fixing-proclaim.md
    - Starting Recording and Livestreaming: docs/general/starting-recording-livestream.md
    - During the Service: docs/general/during-service.md
    - Stopping Recording and Livestreaming: docs/general/stopping-recording-livestream.md
    - Shutting Down and Packing Up Computer / Cameras / Sound System / Projector: docs/general/shutting-down-packing-up.md
    - Switching To Church Internet: docs/general/internet-2.md
    - Stream Deck Icons: docs/general/stream-deck.md
    - Changing Audio Output Device: docs/general/audio-output.md
  - Cameras:
    - docs/cameras/index.md
    - PTZ Camera:
      - docs/cameras/PTZ/index.md
      - Logging into Camera: docs/cameras/PTZ/logging_in.md
      - Listing of Current Presets: docs/cameras/PTZ/presets_list.md
      - Setting Camera Presets: docs/cameras/PTZ/presets_add.md
      - Camera Settings: 
        - docs/cameras/PTZ/settings/index.md
        - (list settings that are noteworthy here): docs/cameras/PTZ/settings/list.md
    - Mevo Cameras:
      - docs/cameras/mevo/index.md
      - Connecting to Cameras: docs/cameras/mevo/connecting.md
      - Camera Settings:
        - docs/cameras/mevo/settings/index.md
        - (list settings that are noteworthy here): docs/cameras/mevo/settings/list.md
  - Computer:
    - docs/computer/index.md
    - OBS Studio:
      - docs/computer/OBS/index.md
      - Streaming Instance:
        - docs/computer/OBS/streaming/index.md
        - Recording Settings: docs/computer/OBS/streaming/recording.md
        - Streaming Settings: docs/computer/OBS/streaming/streaming.md
        - Outgoing Stream to All Cameras Instance: docs/computer/OBS/streaming/virtual_camera.md
        - Scenes:
          - docs/computer/OBS/streaming/scenes/index.md
          - Default Scenes for Our Use: docs/computer/OBS/streaming/scenes/default.md
        - Sources: 
          - docs/computer/OBS/streaming/sources/index.md
          - Mevo Cameras: docs/computer/OBS/streaming/sources/mevo_cameras.md
          - PTZ Camera: docs/computer/OBS/streaming/sources/PTZ_camera.md
          - Proclaim: docs/computer/OBS/streaming/sources/proclaim.md
          - Powerpoint: docs/computer/OBS/streaming/sources/powerpoint.md
          - Sound System: docs/computer/OBS/streaming/sources/sound_system.md
      - All Cameras Instance:
        - docs/computer/OBS/all_cams/index.md
        - Recording Settings: docs/computer/OBS/all_cams/recording.md
        - Sources: 
          - docs/computer/OBS/all_cams/sources/index.md
          - Mevo Cameras: docs/computer/OBS/all_cams/sources/mevo_cameras.md
          - PTZ Camera: docs/computer/OBS/all_cams/sources/PTZ_camera.md
          - Proclaim: docs/computer/OBS/all_cams/sources/proclaim.md
          - Powerpoint: docs/computer/OBS/all_cams/sources/powerpoint.md
          - Sound System: docs/computer/OBS/all_cams/sources/sound_system.md
          - Outgoing Streams: docs/computer/OBS/all_cams/sources/outgoing_stream.md
      - Plugins:
        - docs/computer/OBS/plugins/index.md
        - Multi Output: docs/computer/OBS/plugins/multi_output.md
        - NDI: docs/computer/OBS/plugins/ndi_tools.md
        - PTZ Controls: docs/computer/OBS/plugins/ptz_controls.md
    - Proclaim:
      - docs/computer/proclaim/index.md
      - Opening Slides for Current Week: docs/computer/proclaim/opening_slides.md
      - Starting Slideshow: docs/computer/proclaim/starting_slideshow.md
      - Screen Settings: docs/computer/proclaim/screen_settings.md
      - NDI Settings: docs/computer/proclaim/NDI_settings.md
    - Streamdeck:
      - docs/computer/streamdeck/index.md
      - OBS Scenes: docs/computer/streamdeck/OBS_scenes.md
      - OBS Recording & Streaming Controls: docs/computer/streamdeck/recording_streaming_controls.md
      - PTZ Camera Preset Locations:
        - docs/computer/streamdeck/PTZ_camera/index.md
        - Adding Presets: docs/computer/streamdeck/PTZ_camera/adding_presets.md
        - Listing of Current Presets: docs/computer/streamdeck/PTZ_camera/presets_list.md
    - Streaming Locations:
      - docs/computer/streams/index.md
      - YouTube:
        - docs/computer/streams/youtube/index.md
        - Scheduling Livestream: docs/computer/streams/youtube/scheduling.md
        - Starting Livestream: docs/computer/streams/youtube/starting.md
        - Stopping Livestream: docs/computer/streams/youtube/stopping.md
      - Facebook Live: 
        - docs/computer/streams/facebook/index.md
        - Scheduling Livestream: docs/computer/streams/facebook/scheduling.md
        - Starting Livestream: docs/computer/streams/facebook/starting.md
        - Stopping Livestream: docs/computer/streams/facebook/stopping.md
    - Performing Maintanince:
      - docs/computer/maintanince/index.md
      - CCleaner: docs/computer/maintanince/ccleaner.md
      - Dell Support Assist: docs/computer/maintanince/dell_support_assist.md
      - Windows Update: docs/computer/maintanince/windows_update.md
      - Nvidia Graphics Card Update: docs/computer/maintanince/nvidia_update.md
      - Proclaim Updates: docs/computer/maintanince/proclaim_updates.md
      - OBS Updates:
        - docs/computer/maintanince/OBS/index.md
        - Streaming Instance: docs/computer/maintanince/streaming_update.md
        - All Cameras Instance: docs/computer/maintanince/all_cams_update.md
        - Plugin Updates:
          - docs/computer/maintanince/OBS/plugins/index.md
          - Multi Output: docs/computer/maintanince/OBS/plugins/multi_output.md
          - NDI: docs/computer/maintanince/OBS/plugins/ndi_tools.md
          - PTZ Controls: docs/computer/maintanince/OBS/plugins/ptz_controls.md
      - Elgato:
        - docs/computer/maintanince/elgato/index.md
        - Stream Deck: docs/computer/maintanince/elgato/streamdeck.md
        - Capture Card: docs/computer/maintanince/elgato/capture_card.md
  - Advanced Information:
    - docs/advanced/index.md
    - Technology Listing:
      - docs/advanced/technology/index.md
      - Hardware Listing: docs/advanced/technology/hardware.md
      - Software Listing: docs/advanced/technology/software.md
      - Technology Not In Use: docs/advanced/technology/not_in_use.md
    - Cabling Diagrams:
      - docs/advanced/cabling/index.md
      - AV System: docs/advanced/cabling/AV_system.md
      - Networking: docs/advanced/cabling/networking.md
      - Computer: docs/advanced/cabling/computer.md
    - Password Repository:
      - docs/advanced/passwords/index.md
      - Accessing: docs/advanced/passwords/accessing.md
      - Viewing Passwords: docs/advanced/passwords/viewing.md
      - Adding Passwords: docs/advanced/passwords/addng.md
      - Editing Passwords: docs/advanced/passwords/editing.md
      - Removing Passwords: docs/advanced/passwords/removing.md
    - Backup Files Repository: 
      - docs/advanced/backups/index.md
      - Router: docs/advanced/backups/router_configs.md
      - PTZ Camera: docs/advanced/backups/ptz_camera_configs.md
      - OBS:
        - docs/advanced/backups/OBS/index.md
        - Streaming Instance Scenes: docs/advanced/backups/OBS/streaming_scenes.md
        - All Cameras Entire Instance: docs/advanced/backups/OBS/all_cameras.md
      - Password Repository:
        - docs/advanced/backups/passwords/index.md
        - Database: docs/advanced/backups/passwords/database.md
        - Security Key: docs/advanced/backups/passwords/security_key.md
    - Router: 
      - docs/advanced/router/index.md
      - Settings:
        - docs/advanced/router/settings/index.md
        - (list settings that are noteworthy here): docs/advanced/router/settings/list.md
  - PDF: pdf/document.pdf