site_name: WPC Tech Docs

repo_name: jackveney/wpc-tech-docs
repo_url: https://github.com/jackveney/wpc-tech-docs
edit_uri: ""

site_description: Westminster Presbyterian Church Wooster, Ohio Technology Documentation
site_author: Jack Veney
theme:
  name: material
  custom_dir: material/
  features:
    - navigation.tabs
  logo: assets/WPC_logo.png
  favicon: assets/WPC_logo.png
  icon:
    repo: fontawesome/brands/github
  language: en

markdown_extensions:
  - tables

copyright: Copyright &copy; 2022 Jack Veney - Westminster Presbyterian Church Wooster, Ohio
plugins:
  - search:
      lang: en
  - redirects:
      redirect_maps:
        tech-docs.md: TechDocs/index.md
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true 
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
#      combined: true

extra_css:
    - css/extra.css

# Page tree
nav:
  - Home: index.md
  - About: about.md
  - Technology Documentation:
    - Home: TechDocs/index.md
    - Listing of Technology Hardware Parts: TechDocs/parts-listing.md
    - Fixing Proclaim for OBS Studio: TechDocs/fixing-proclaim.md
    - Changing Audio Output Device: TechDocs/audio-output.md
    - Switching To COW Internet: TechDocs/internet.md
    - Switching To Church Internet: TechDocs/internet-2.md
    - Setting Up and Powering On: TechDocs/setting-up-powering-on.md
#  - Administration: 
#    - 'Home': 'Administration/index.md'
#    - 'User Guide': 
#      - 'Getting Started': 'Administration/getting-started.md'
#      - 'OPAC': 'Administration/opacs.md'
#      - 'Library': 'Administration/libraries.md'
#      - 'Cataloging (Books)': 'Administration/cataloging.md'
#      - 'Members (Patrons)': 'Administration/members.md'
#      - 'Circulations (Loans)': 'Administration/circulations.md'
#      - 'Fees & Payments': 'Administration/fees-payments.md'
#      - 'Barcode Labels': 'Administration/barcode-labels.md'
#      - 'Reports': 'Administration/reports.md'
#      - 'Member Area': 'Administration/member-area.md'
#      - 'Users': 'Administration/users.md'
#      - 'Bulk Actions': 'Administration/bulk-actions.md'
#    - 'Contributing': 'Administration/contribute.md'
#    - 'About': 'Administration/about.md'
#    - 'License': 'Administration/license.md'
