site_name: WPC Technology Documentation

repo_name: jackveney/wpc-tech-docs
repo_url: https://github.com/jackveney/wpc-tech-docs
edit_uri: ""
extra_css:
  - 'css/extra.css'

site_description: A reference for the technology located in Mackey Hall used for running and livestreaming services.
site_author: Jack Veney
theme:
  name: material
  custom_dir: material/
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: assets/WPC_logo.png
  favicon: assets/WPC_logo.png
  icon:
    repo: fontawesome/brands/github
  language: en
  static_templates:
    - 404.html

markdown_extensions:
  - tables
  - pymdownx.keys
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

copyright: Copyright &copy; 2022 Jack Veney - Westminster Presbyterian Church Wooster, Ohio
plugins:
  - search:
      lang: en
  - redirects:
      redirect_maps:
        tech-docs.md: TechDocs/index.md
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true
  - with-pdf:
      #author: WHO
      #copyright: ANY TEXT
      #
      cover: true
      back_cover: true
      #cover_title: TITLE TEXT
      cover_subtitle: 2022 Updates
      cover_logo: assets/images/banner.png
      #custom_template_path: TEMPLATES PATH
      #
      toc_title: Table of Contents
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      exclude_pages:
      #    - 'TechDocs/parts-listing'
      #    - 'about/'
      #    - 'PTZ_Camera/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      #render_js: true
      #headless_chrome_path: headless-chromium
      #
      #output_path: any-place/document.pdf
      #enabled_if_env: ENABLE_PDF_EXPORT
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true

# Page tree
nav:
  - Home: index.md
  - About: about.md
  - General Instructions:
    - Home: TechDocs/index.md
    - Listing of Technology Hardware Parts: TechDocs/parts-listing.md
    - Switching To COW Internet: TechDocs/internet.md
    - Setting Up and Powering On Computer / Cameras / Sound System / Projector: TechDocs/setting-up-powering-on.md
    - Connecting iPad to Sound System: TechDocs/ipad-sound-system.md
    - Fixing Proclaim for OBS Studio: TechDocs/fixing-proclaim.md
    - Starting Recording and Livestreaming: TechDocs/starting-recording-livestream.md
    - During the Service: TechDocs/during-service.md
    - Stopping Recording and Livestreaming: TechDocs/stopping-recording-livestream.md
    - Shutting Down and Packing Up Computer / Cameras / Sound System / Projector: TechDocs/shutting-down-packing-up.md
    - Switching To Church Internet: TechDocs/internet-2.md
    - Stream Deck Icons: TechDocs/stream-deck.md
    - Changing Audio Output Device: TechDocs/audio-output.md
  - Cameras: TechDocs/cameras/index.md
    - PTZ Camera: TechDocs/cameras/PTZ/index.md
      - Logging into Camera: TechDocs/cameras/PTZ/logging_in.md
      - Listing of Current Presets: TechDocs/cameras/PTZ/presets_list.md
      - Setting Camera Presets: TechDocs/cameras/PTZ/presets_add.md
      - Adding Camera Presets to Streamdeck: TechDocs/cameras/PTZ/presets_streamdeck.md
      - Camera Settings: TechDocs/cameras/PTZ/settings/index.md
        - (list settings that are noteworthy here): TechDocs/cameras/PTZ/settings/list.md
    - Mevo Cameras: TechDocs/cameras/mevo/index.md
      - Connecting to Cameras: TechDocs/cameras/mevo/connecting.md
      - Camera Settings: TechDocs/cameras/mevo/settings/index.md
        - (list settings that are noteworthy here): TechDocs/cameras/mevo/settings/list.md
  - Computer: TechDocs/computer/index.md
    - OBS Studio: TechDocs/computer/index.md
      - Streaming Instance: TechDocs/computer/index.md
        - Recording Settings: TechDocs/computer/index.md
        - Streaming Settings: TechDocs/computer/index.md
        - Outgoing Stream to "Security View" Instance: TechDocs/computer/index.md
        - Adding Scenes: TechDocs/computer/index.md
        - Adding Sources: TechDocs/computer/index.md
          - Mevo Cameras: TechDocs/computer/index.md
          - PTZ Camera: TechDocs/computer/index.md
          - Proclaim: TechDocs/computer/index.md
          - Powerpoint: TechDocs/computer/index.md
          - Sound System: TechDocs/computer/index.md
      - "Security View" Instance: TechDocs/computer/index.md
        - Recording Settings: TechDocs/computer/index.md
        - Sources: TechDocs/computer/index.md
          - Mevo Cameras: TechDocs/computer/index.md
          - PTZ Camera: TechDocs/computer/index.md
          - Proclaim: TechDocs/computer/index.md
          - Powerpoint: TechDocs/computer/index.md
          - Sound System: TechDocs/computer/index.md
          - Outgoing Streams: TechDocs/computer/index.md
    - Proclaim: TechDocs/computer/index.md
      - Opening Slides for Current Week: TechDocs/computer/index.md
      - Starting Slides: TechDocs/computer/index.md
      - Screen Settings: TechDocs/computer/index.md
      - NDI Settings: TechDocs/computer/index.md
    - Streamdeck: TechDocs/computer/index.md
      - OBS Scenes: TechDocs/computer/index.md
      - OBS Recording & Streaming Controls: TechDocs/computer/index.md
      - PTZ Camera Presets: TechDocs/computer/index.md
    - Youtube: TechDocs/computer/index.md
      - Scheduling Livestream: TechDocs/computer/index.md
      - Starting Livestream: TechDocs/computer/index.md
      - Stopping Livestream: TechDocs/computer/index.md
    - Facebook Live: TechDocs/computer/index.md
      - Scheduling Livestream: TechDocs/computer/index.md
      - Starting Livestream: TechDocs/computer/index.md
      - Stopping Livestream: TechDocs/computer/index.md
    - Performing Maintanince: TechDocs/computer/index.md
      - CCleaner: TechDocs/computer/index.md
      - Dell Support Assist: TechDocs/computer/index.md
      - Windows Update: TechDocs/computer/index.md
      - Graphics Card Update: TechDocs/computer/index.md
      - Proclaim Updates: TechDocs/computer/index.md
      - OBS Updates: TechDocs/computer/index.md
        - Streaming Instance: TechDocs/computer/index.md
        - "Security View" Instance: TechDocs/computer/index.md
        - Plugins: TechDocs/computer/index.md
  - Advanced Information: TechDocs/advanced/index.md
    - Technology Listing: TechDocs/computer/index.md
      - Hardware Listing: TechDocs/computer/index.md
      - Software Listing: TechDocs/computer/index.md
      - Technology Not In Use: TechDocs/computer/index.md
    - Cabling Diagrams: TechDocs/computer/index.md
      - AV System: TechDocs/computer/index.md
      - Networking: TechDocs/computer/index.md
    - Password Repository: TechDocs/computer/index.md
      - Accessing: TechDocs/computer/index.md
      - Adding Passwords: TechDocs/computer/index.md
      - Editing Passwords: TechDocs/computer/index.md
      - Removing Passwords: TechDocs/computer/index.md
    - Router: TechDocs/computer/index.md
      - Settings: TechDocs/computer/index.md
        - (list settings that are noteworthy here): TechDocs/computer/index.md
    - Backup Files Repository: TechDocs/computer/index.md
      - (figure out what to go here): TechDocs/computer/index.md
  - PDF: pdf/document.pdf
