site_name: WPC Technology Documentation

repo_name: jackveney/wpc-tech-docs
repo_url: https://github.com/jackveney/wpc-tech-docs
edit_uri: ""
extra_css:
  - 'css/extra.css'

site_description: A reference for the technology located in Mackey Hall used for running and livestreaming services.
site_author: Jack Veney
theme:
  name: material
  custom_dir: material/
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: assets/WPC_logo.png
  favicon: assets/WPC_logo.png
  icon:
    repo: fontawesome/brands/github
  language: en
  static_templates:
    - 404.html

markdown_extensions:
  - tables
  - pymdownx.keys
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

copyright: Copyright &copy; 2022 Jack Veney - Westminster Presbyterian Church Wooster, Ohio
plugins:
  - search:
      lang: en
  - redirects:
      redirect_maps:
        tech-docs.md: docs/index.md
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true
  - with-pdf:
      #author: WHO
      #copyright: ANY TEXT
      #
      cover: true
      back_cover: true
      #cover_title: TITLE TEXT
      cover_subtitle: 2022 Updates
      cover_logo: assets/images/banner.png
      #custom_template_path: TEMPLATES PATH
      #
      toc_title: Table of Contents
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      exclude_pages:
      #    - 'docs/parts-listing'
      #    - 'about/'
      #    - 'PTZ_Camera/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      #render_js: true
      #headless_chrome_path: headless-chromium
      #
      #output_path: any-place/document.pdf
      #enabled_if_env: ENABLE_PDF_EXPORT
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true

# Page tree
nav:
  - Home: index.md
  - About: about.md
  - General Instructions: docs/general/index.md
    - Listing of Technology Hardware Parts: docs/general/parts-listing.md
    - Switching To COW Internet: docs/general/internet.md
    - Setting Up and Powering On Computer / Cameras / Sound System / Projector: docs/general/setting-up-powering-on.md
    - Connecting iPad to Sound System: docs/general/ipad-sound-system.md
    - Fixing Proclaim for OBS Studio: docs/general/fixing-proclaim.md
    - Starting Recording and Livestreaming: docs/general/starting-recording-livestream.md
    - During the Service: docs/general/during-service.md
    - Stopping Recording and Livestreaming: docs/general/stopping-recording-livestream.md
    - Shutting Down and Packing Up Computer / Cameras / Sound System / Projector: docs/general/shutting-down-packing-up.md
    - Switching To Church Internet: docs/general/internet-2.md
    - Stream Deck Icons: docs/general/stream-deck.md
    - Changing Audio Output Device: docs/general/audio-output.md
  # - Cameras: 
  #   - PTZ Camera: 
  #     - Logging into Camera: docs/cameras/PTZ/logging_in.md
  #     - Listing of Current Presets: docs/cameras/PTZ/presets_list.md
  #     - Setting Camera Presets: docs/cameras/PTZ/presets_add.md
  #     - Adding Camera Presets to Streamdeck: docs/cameras/PTZ/presets_streamdeck.md
  #     - Camera Settings: 
  #       - (list settings that are noteworthy here): docs/cameras/PTZ/settings/list.md
  #   - Mevo Cameras: 
  #     - Connecting to Cameras: docs/cameras/mevo/connecting.md
  #     - Camera Settings: 
  #       - (list settings that are noteworthy here): docs/cameras/mevo/settings/list.md
  # - Computer: 
  #   - OBS Studio: 
  #     - Streaming Instance: 
  #       - Recording Settings: docs/computer/index.md
  #       - Streaming Settings: docs/computer/index.md
  #       - Outgoing Stream to "Security View" Instance: docs/computer/index.md
  #       - Adding Scenes: docs/computer/index.md
  #       - Adding Sources: 
  #         - Mevo Cameras: docs/computer/index.md
  #         - PTZ Camera: docs/computer/index.md
  #         - Proclaim: docs/computer/index.md
  #         - Powerpoint: docs/computer/index.md
  #         - Sound System: docs/computer/index.md
  #     - Security View Instance: 
  #       - Recording Settings: docs/computer/index.md
  #       - Sources: 
  #         - Mevo Cameras: docs/computer/index.md
  #         - PTZ Camera: docs/computer/index.md
  #         - Proclaim: docs/computer/index.md
  #         - Powerpoint: docs/computer/index.md
  #         - Sound System: docs/computer/index.md
  #         - Outgoing Streams: docs/computer/index.md
  #   - Proclaim: 
  #     - Opening Slides for Current Week: docs/computer/index.md
  #     - Starting Slides: docs/computer/index.md
  #     - Screen Settings: docs/computer/index.md
  #     - NDI Settings: docs/computer/index.md
  #   - Streamdeck: 
  #     - OBS Scenes: docs/computer/index.md
  #     - OBS Recording & Streaming Controls: docs/computer/index.md
  #     - PTZ Camera Presets: docs/computer/index.md
  #   - Youtube: 
  #     - Scheduling Livestream: docs/computer/index.md
  #     - Starting Livestream: docs/computer/index.md
  #     - Stopping Livestream: docs/computer/index.md
  #   - Facebook Live: 
  #     - Scheduling Livestream: docs/computer/index.md
  #     - Starting Livestream: docs/computer/index.md
  #     - Stopping Livestream: docs/computer/index.md
  #   - Performing Maintanince:
  #     - CCleaner: docs/computer/index.md
  #     - Dell Support Assist: docs/computer/index.md
  #     - Windows Update: docs/computer/index.md
  #     - Graphics Card Update: docs/computer/index.md
  #     - Proclaim Updates: docs/computer/index.md
  #     - OBS Updates:
  #       - Streaming Instance: docs/computer/index.md
  #       - Security View Instance: docs/computer/index.md
  #       - Plugins: docs/computer/index.md
  # - Advanced Information: 
  #   - Technology Listing: 
  #     - Hardware Listing: docs/computer/index.md
  #     - Software Listing: docs/computer/index.md
  #     - Technology Not In Use: docs/computer/index.md
  #   - Cabling Diagrams: 
  #     - AV System: docs/computer/index.md
  #     - Networking: docs/computer/index.md
  #   - Password Repository: 
  #     - Accessing: docs/computer/index.md
  #     - Adding Passwords: docs/computer/index.md
  #     - Editing Passwords: docs/computer/index.md
  #     - Removing Passwords: docs/computer/index.md
  #   - Router: 
  #     - Settings: 
  #       - (list settings that are noteworthy here): docs/computer/index.md
  #   - Backup Files Repository: 
  #     - (figure out what to go here): docs/computer/index.md
  - PDF: pdf/document.pdf